unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

# Sensible settings
set -g history-limit 10000
set -g mouse on
setw -g mode-keys vi

# Status bar customization
set -g status-bg colour235
set -g status-fg colour136
set -g status-left-length 40
set -g status-right-length 100
set -g status-interval 5
set -g status-left '#[fg=colour46]#H#[default]'
set -g status-right '#[fg=colour136] %Y-%m-%d #[fg=colour136] %H:%M #[default]'

# Pane splitting (default bindings)
# " for horizontal split
# % for vertical split

# Seamless pane navigation with hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Reload config file
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"
